// Derives src/data/countries.ts from data/countries.json.
//
// Emits a single fully-populated COUNTRY_DATA record (every country, not a
// Partial subset) keyed by ISO 3166-1 alpha-2 code, carrying the reference
// metadata GeoNames gives us — including the level-1/level-2 administrative code division-type labels
// that drive level1 in src/utils/address.ts.
//
// Run with: bun run scripts/gen-countries.ts
import { spawn } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// Biome force-excludes src/data, so it won't format these files even via
// `--stdin-file-path` pointing at the real path (an excluded path makes Biome
// echo stdin unchanged). Format the source through stdin under a neutral,
// non-excluded filename — Biome only needs the extension to pick the formatter —
// so it applies the repo's real config before we write.
function formatTs(source: string): Promise<string> {
  return new Promise((resolvePromise, reject) => {
    const child = spawn("bunx", ["biome", "format", "--stdin-file-path=gen-output.ts"]);
    let out = "";
    let err = "";
    child.stdout.on("data", (d) => {
      out += d;
    });
    child.stderr.on("data", (d) => {
      err += d;
    });
    child.on("error", reject);
    child.on("close", (code) => (code === 0 ? resolvePromise(out) : reject(new Error(err || `biome exited ${code}`))));
    child.stdin.end(source);
  });
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const inFile = resolve(__dirname, "../data/countries.json");
const outFile = resolve(__dirname, "../src/data/countries.ts");

type DivisionLabel = { en: string | null; local: string | null };
type Country = {
  code: string;
  iso3: string;
  name: string;
  continent: string;
  currencyCode: string;
  currencyName: string;
  postalCodeRegex: string | null;
  languages: string[];
  administrativeLabels: {
    level1: DivisionLabel | null;
    level2: DivisionLabel | null;
  };
};

const countries: Country[] = JSON.parse(await readFile(inFile, "utf8"));
countries.sort((a, b) => a.code.localeCompare(b.code));

// GeoNames reports a single dominant level1 category, but some countries mix
// two (or more) distinct kinds of level-1 division. For these we override the
// English level1 label with the combined form so level1
// in src/utils/address.ts reads correctly. Keyed by alpha-2 code.
const LEVEL1_LABEL_OVERRIDES: Record<string, string> = {
  CA: "Province/Territory",
  AU: "State/Territory",
  VN: "Province/Municipality",
  SL: "Province/Area",
  PA: "Province/Indigenous region",
  KP: "Province/Municipality",
  MM: "Region/State",
  MD: "District/Municipality",
  MY: "State/Federal territory",
  MV: "Atoll/City",
  IE: "County/City",
  ET: "Region/Chartered city",
  AZ: "District/City",
  AG: "Parish/Dependency",
};

for (const c of countries) {
  const override = LEVEL1_LABEL_OVERRIDES[c.code];
  if (override)
    c.administrativeLabels.level1 = {
      en: override,
      local: c.administrativeLabels.level1?.local ?? null,
    };
}

const header = `// AUTO-GENERATED by scripts/gen-countries.ts — do not edit by hand.
// Regenerate with: bun run gen:countries

export type DivisionLabel = { en: string | null; local: string | null };

export interface CountryData {
  code: string;
  iso3: string;
  name: string;
  continent: string;
  currencyCode: string;
  currencyName: string;
  postalCodeRegex: string | null;
  languages: string[];
  administrativeLabels: {
    level1: DivisionLabel | null;
    level2: DivisionLabel | null;
  };
}
`;

// Pretty-print each country as an object literal; the whole file is then run
// through Biome (see formatTs) so the indentation/spacing matches the repo.
const entries = countries
  .map((c) => `  ${JSON.stringify(c.code)}: ${JSON.stringify(c, null, 2).replace(/\n/g, "\n  ")},`)
  .join("\n");

// Emit the alpha-2 codes as a readonly tuple so CountryCode is a literal union
// (every country GeoNames knows about) rather than a bare string — this is the
// key type for COUNTRY_DATA and the source of COUNTRY_CODES re-exported by
// src/utils/address.ts.
const codesPerLine = 12;
const codeRows: string[] = [];
for (let i = 0; i < countries.length; i += codesPerLine)
  codeRows.push(
    `  ${countries
      .slice(i, i + codesPerLine)
      .map((c) => JSON.stringify(c.code))
      .join(", ")},`,
  );
const codesBlock = `// ISO 3166-1 alpha-2 code for every country GeoNames knows about.
export const COUNTRY_CODES = [
${codeRows.join("\n")}
] as const;

export type CountryCode = (typeof COUNTRY_CODES)[number];
`;

const body = `${codesBlock}
// Fully populated: every country GeoNames knows about, keyed by alpha-2 code.
export const COUNTRY_DATA: Record<CountryCode, CountryData> = {
${entries}
};
`;

await writeFile(outFile, await formatTs(`${header}\n${body}`));
console.log(`wrote ${outFile} (${countries.length} countries)`);
