import { StyleSheet } from 'react-native';

// Shared styles + design tokens for the demo app, extracted so no single demo
// file exceeds the line budget.

export const s = StyleSheet.create({
  page: { flex: 1, backgroundColor: '#f8fafc' },
  pageContent: { flexGrow: 1 },
  container: { maxWidth: 520, width: '100%', alignSelf: 'center', padding: 24, gap: 16 },
  h1: { fontSize: 22, fontWeight: '700', color: '#0f172a' },
  sub: { fontSize: 13, color: '#64748b', marginTop: -8 },
  tabs: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  tab: { paddingHorizontal: 12, paddingVertical: 7, borderRadius: 999, backgroundColor: '#e2e8f0' },
  tabActive: { backgroundColor: '#4f46e5' },
  tabText: { fontSize: 13, fontWeight: '600', color: '#475569' },
  tabTextActive: { color: '#ffffff' },
  controls: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    padding: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 8,
  },
  wrapper: { gap: 12 },
  controlGroup: { gap: 4 },
  legend: { fontSize: 10, fontWeight: '700', letterSpacing: 0.6, color: '#64748b', textTransform: 'uppercase' },
  option: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  radioDot: {
    width: 14,
    height: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#94a3b8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioDotOn: { borderColor: '#4f46e5' },
  radioInner: { width: 8, height: 8, borderRadius: 999, backgroundColor: '#4f46e5' },
  radioSquare: { borderRadius: 4 },
  toggleCheck: { fontSize: 10, color: '#4f46e5', fontWeight: '700' },
  optionText: { fontSize: 13, color: '#334155' },
  status: { borderWidth: 1, borderRadius: 8, padding: 10 },
  statusValid: { backgroundColor: '#d1fae5', borderColor: '#10b981' },
  statusInvalid: { backgroundColor: '#fee2e2', borderColor: '#ef4444' },
  statusText: { fontWeight: '600', fontSize: 13 },
  statusTextValid: { color: '#065f46' },
  statusTextInvalid: { color: '#991b1b' },
  sectionLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: '#9ca3af',
    textTransform: 'uppercase',
    marginTop: 8,
  },
  json: { backgroundColor: '#0f172a', borderRadius: 8, padding: 12 },
  jsonText: { fontFamily: 'monospace', fontSize: 12, color: '#e2e8f0' },
  card: { backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 10, padding: 16 },
  btn: { backgroundColor: '#4f46e5', borderRadius: 8, paddingVertical: 8, paddingHorizontal: 14, alignSelf: 'flex-start' },
  btnText: { color: '#ffffff', fontWeight: '600', fontSize: 13 },
});

export const custom = StyleSheet.create({
  root: { gap: 14 },
  field: { gap: 6 },
  label: { fontSize: 12, fontWeight: '700', letterSpacing: 0.4, color: '#0f766e', textTransform: 'uppercase' },
  input: {
    borderWidth: 2,
    borderColor: '#5eead4',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontSize: 15,
    backgroundColor: '#f0fdfa',
    color: '#134e4a',
  },
  inputInvalid: { borderColor: '#f43f5e', backgroundColor: '#fff1f2' },
  error: { fontSize: 12, color: '#e11d48', fontWeight: '600' },
});
